# Generated by Django 6.0.7 on 2026-07-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='short_description',
            new_name='about_description',
        ),
    ]
